CREATE DATABASE IF NOT EXISTS php_api CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE php_api;
CREATE TABLE IF NOT EXISTS product (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  size INT NOT NULL,
  is_available TINYINT(1) NOT NULL DEFAULT 1
);
